### ISSUE TITLE
Message query

### ISSUE THREAD

**Issue by moschlar** [derf/Travel-Status-DE-URA#6]
Just a quick note and maybe a reminder for myself to work on this:

The MVG Mainz also has the ability to show additional messages per stop.
A query URL looks like `/interfaces/ura/instant_V1?StopAlso=false&ReturnList=messageuuid,messagepriority,messagetext,starttime,expiretime&StopId=627`.
This might be interesting to implement too.

**Comment by derf** [comment]
Indeed. The ASEAG instance also supports this (though I'm not quite sure whether it is limited to instant_V2), but I didn't get around to implementing support for them yet.

**Comment by derf** [comment]
works on all known URA installations, so initial support is present now.
